name: Nearboard CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn
      - run: yarn build:contract
      - run: yarn test:integration