name: Nearboard CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn
      - run: cd contract && yarn build
      - run: cd integration-tests && npm test -- -- \"../contract/build/nearboard.wasm\"