name: Nearboard CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  test_pull_request:
    runs-on: node-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build:contract
      - run: yarn test:integration